global:
  image: alpine:latest
  trigger:
    branch:
      - "*"
jobs:
  - name: install
    commands:
      - env
      - mkdir test
      - touch test/test.md
      - echo test > test/test.md
      - mkdir foo
      - touch foo/bar.md
      - echo foobar > foo/bar.md
    artifacts:
      - name: test
      - name: foo

  - name: list
    commands:
      - ls -lah
      - echo foo/bar.md
      - echo test/test.md
      - env
    resources:
      - name: test
      - name: foo