global:
  image: alpine:latest
  trigger:
    branch:
      - "*"
jobs:
  - name: install
    commands:
      - env
      - mkdir test
      - touch test/test.md
      - echo test > test/test.md
    artifacts:
      - name: test

  - name: list
    commands:
      - ls -lah
      - env
    resources:
      - name: test